defmodule BACnet.Protocol.Constants.ObjectsSupported do
  @moduledoc false

  use BACnet.Macro, exception: BACnet.Protocol.Constants.ConstantError

  defconstant(:object_types_supported, :analog_input, 0x00)
  defconstant(:object_types_supported, :analog_output, 0x01)
  defconstant(:object_types_supported, :analog_value, 0x02)
  defconstant(:object_types_supported, :binary_input, 0x03)
  defconstant(:object_types_supported, :binary_output, 0x04)
  defconstant(:object_types_supported, :binary_value, 0x05)
  defconstant(:object_types_supported, :calendar, 0x06)
  defconstant(:object_types_supported, :command, 0x07)
  defconstant(:object_types_supported, :device, 0x08)
  defconstant(:object_types_supported, :event_enrollment, 0x09)
  defconstant(:object_types_supported, :file, 0x0A)
  defconstant(:object_types_supported, :group, 0x0B)
  defconstant(:object_types_supported, :loop, 0x0C)
  defconstant(:object_types_supported, :multi_state_input, 0x0D)
  defconstant(:object_types_supported, :multi_state_output, 0x0E)
  defconstant(:object_types_supported, :notification_class, 0x0F)
  defconstant(:object_types_supported, :program, 0x10)
  defconstant(:object_types_supported, :schedule, 0x11)
  defconstant(:object_types_supported, :averaging, 0x12)
  defconstant(:object_types_supported, :multi_state_value, 0x13)
  defconstant(:object_types_supported, :trend_log, 0x14)
  defconstant(:object_types_supported, :life_safety_point, 0x15)
  defconstant(:object_types_supported, :life_safety_zone, 0x16)
  defconstant(:object_types_supported, :accumulator, 0x17)
  defconstant(:object_types_supported, :pulse_converter, 0x18)
  defconstant(:object_types_supported, :event_log, 0x19)
  defconstant(:object_types_supported, :global_group, 0x1A)
  defconstant(:object_types_supported, :trend_log_multiple, 0x1B)
  defconstant(:object_types_supported, :load_control, 0x1C)
  defconstant(:object_types_supported, :structured_view, 0x1D)
  defconstant(:object_types_supported, :access_door, 0x1E)
  defconstant(:object_types_supported, :timer, 0x1F)
  defconstant(:object_types_supported, :access_credential, 0x20)
  defconstant(:object_types_supported, :access_point, 0x21)
  defconstant(:object_types_supported, :access_rights, 0x22)
  defconstant(:object_types_supported, :access_user, 0x23)
  defconstant(:object_types_supported, :access_zone, 0x24)
  defconstant(:object_types_supported, :credential_data_input, 0x25)
  defconstant(:object_types_supported, :network_security, 0x26)
  defconstant(:object_types_supported, :bitstring_value, 0x27)
  defconstant(:object_types_supported, :character_string_value, 0x28)
  defconstant(:object_types_supported, :date_pattern_value, 0x29)
  defconstant(:object_types_supported, :date_value, 0x2A)
  defconstant(:object_types_supported, :datetime_pattern_value, 0x2B)
  defconstant(:object_types_supported, :datetime_value, 0x2C)
  defconstant(:object_types_supported, :integer_value, 0x2D)
  defconstant(:object_types_supported, :large_analog_value, 0x2E)
  defconstant(:object_types_supported, :octet_string_value, 0x2F)
  defconstant(:object_types_supported, :positive_integer_value, 0x30)
  defconstant(:object_types_supported, :time_pattern_value, 0x31)
  defconstant(:object_types_supported, :time_value, 0x32)
  defconstant(:object_types_supported, :notification_forwarder, 0x33)
  defconstant(:object_types_supported, :alert_enrollment, 0x34)
  defconstant(:object_types_supported, :channel, 0x35)
  defconstant(:object_types_supported, :lighting_output, 0x36)
  defconstant(:object_types_supported, :binary_lighting_output, 0x37)
  defconstant(:object_types_supported, :network_port, 0x38)
  defconstant(:object_types_supported, :elevator_group, 0x39)
  defconstant(:object_types_supported, :escalator, 0x3A)
  defconstant(:object_types_supported, :lift, 0x3B)

  @doc false
  def get_constants() do
    @constants
  end
end
