defmodule BACnet.Protocol.Constants.Services do
  @moduledoc false

  use BACnet.Macro, exception: BACnet.Protocol.Constants.ConstantError

  defconstant(:confirmed_service_choice, :acknowledge_alarm, 0x00)
  defconstant(:confirmed_service_choice, :confirmed_cov_notification, 0x01)
  defconstant(:confirmed_service_choice, :confirmed_event_notification, 0x02)
  defconstant(:confirmed_service_choice, :get_alarm_summary, 0x03)
  defconstant(:confirmed_service_choice, :get_enrollment_summary, 0x04)
  defconstant(:confirmed_service_choice, :subscribe_cov, 0x05)
  defconstant(:confirmed_service_choice, :atomic_read_file, 0x06)
  defconstant(:confirmed_service_choice, :atomic_write_file, 0x07)
  defconstant(:confirmed_service_choice, :add_list_element, 0x08)
  defconstant(:confirmed_service_choice, :remove_list_element, 0x09)
  defconstant(:confirmed_service_choice, :create_object, 0x0A)
  defconstant(:confirmed_service_choice, :delete_object, 0x0B)
  defconstant(:confirmed_service_choice, :read_property, 0x0C)
  defconstant(:confirmed_service_choice, :read_property_multiple, 0x0E)
  defconstant(:confirmed_service_choice, :write_property, 0x0F)
  defconstant(:confirmed_service_choice, :write_property_multiple, 0x10)
  defconstant(:confirmed_service_choice, :device_communication_control, 0x11)
  defconstant(:confirmed_service_choice, :confirmed_private_transfer, 0x12)
  defconstant(:confirmed_service_choice, :confirmed_text_message, 0x13)
  defconstant(:confirmed_service_choice, :reinitialize_device, 0x14)
  defconstant(:confirmed_service_choice, :vt_open, 0x15)
  defconstant(:confirmed_service_choice, :vt_close, 0x16)
  defconstant(:confirmed_service_choice, :vt_data, 0x17)
  defconstant(:confirmed_service_choice, :read_range, 0x1A)
  defconstant(:confirmed_service_choice, :life_safety_operation, 0x1B)
  defconstant(:confirmed_service_choice, :subscribe_cov_property, 0x1C)
  defconstant(:confirmed_service_choice, :get_event_information, 0x1D)
  defconstant(:confirmed_service_choice, :subscribe_cov_property_multiple, 0x1E)
  defconstant(:confirmed_service_choice, :confirmed_cov_notification_multiple, 0x1F)

  defconstant(:unconfirmed_service_choice, :i_am, 0x00)
  defconstant(:unconfirmed_service_choice, :i_have, 0x01)
  defconstant(:unconfirmed_service_choice, :unconfirmed_cov_notification, 0x02)
  defconstant(:unconfirmed_service_choice, :unconfirmed_event_notification, 0x03)
  defconstant(:unconfirmed_service_choice, :unconfirmed_private_transfer, 0x04)
  defconstant(:unconfirmed_service_choice, :unconfirmed_text_message, 0x05)
  defconstant(:unconfirmed_service_choice, :time_synchronization, 0x06)
  defconstant(:unconfirmed_service_choice, :who_has, 0x07)
  defconstant(:unconfirmed_service_choice, :who_is, 0x08)
  defconstant(:unconfirmed_service_choice, :utc_time_synchronization, 0x09)
  defconstant(:unconfirmed_service_choice, :write_group, 0x0A)
  defconstant(:unconfirmed_service_choice, :unconfirmed_cov_notification_multiple, 0x0B)
end
