defmodule BACnet.Protocol.Device.ObjectTypesSupportedTest do
  alias BACnet.Protocol.ApplicationTags.Encoding
  alias BACnet.Protocol.Device.ObjectTypesSupported

  use ExUnit.Case, async: true

  @moduletag :protocol_data_structures

  doctest ObjectTypesSupported

  test "decode ObjectTypesSupported" do
    assert {:ok,
            %ObjectTypesSupported{
              analog_input: true,
              analog_output: true,
              analog_value: true,
              binary_input: true,
              binary_output: true,
              binary_value: true,
              calendar: true,
              command: true,
              device: true,
              event_enrollment: true,
              file: true,
              group: true,
              loop: true,
              multi_state_input: true,
              multi_state_output: true,
              notification_class: true,
              program: true,
              schedule: true,
              averaging: true,
              multi_state_value: true,
              trend_log: true,
              life_safety_point: false,
              life_safety_zone: false,
              accumulator: true,
              pulse_converter: true,
              event_log: true,
              global_group: false,
              trend_log_multiple: true,
              load_control: false,
              structured_view: true,
              access_door: false,
              timer: false,
              access_credential: false,
              access_point: false,
              access_rights: false,
              access_user: false,
              access_zone: false,
              credential_data_input: false,
              network_security: false,
              bitstring_value: true,
              character_string_value: false,
              date_pattern_value: false,
              date_value: false,
              datetime_pattern_value: false,
              datetime_value: false,
              integer_value: true,
              large_analog_value: true,
              octet_string_value: false,
              positive_integer_value: false,
              time_pattern_value: false,
              time_value: false,
              notification_forwarder: false,
              alert_enrollment: false,
              channel: false,
              lighting_output: false,
              binary_lighting_output: false,
              network_port: true,
              elevator_group: false,
              escalator: false,
              lift: false
            }} =
             ObjectTypesSupported.parse(
               bitstring:
                 {true, true, true, true, true, true, true, true, true, true, true, true, true,
                  true, true, true, true, true, true, true, true, false, false, true, true, true,
                  false, true, false, true, false, false, false, false, false, false, false,
                  false, false, true, false, false, false, false, false, true, true, false, false,
                  false, false, false, false, false, false, false, true, false, false, false}
             )
  end

  test "decode ObjectTypesSupported 2" do
    assert {:ok,
            %ObjectTypesSupported{
              analog_input: true,
              analog_output: true,
              analog_value: true,
              binary_input: true,
              binary_output: true,
              binary_value: true,
              calendar: true,
              command: true,
              device: true,
              event_enrollment: true,
              file: true,
              group: true,
              loop: true,
              multi_state_input: true,
              multi_state_output: true,
              notification_class: true,
              program: true,
              schedule: true,
              averaging: true,
              multi_state_value: true,
              trend_log: true,
              life_safety_point: false,
              life_safety_zone: false,
              accumulator: true,
              pulse_converter: true,
              event_log: true,
              global_group: false,
              trend_log_multiple: true,
              load_control: false,
              structured_view: true,
              access_door: false,
              timer: false,
              access_credential: false,
              access_point: false,
              access_rights: false,
              access_user: false,
              access_zone: false,
              credential_data_input: false,
              network_security: false,
              bitstring_value: true,
              character_string_value: false,
              date_pattern_value: false,
              date_value: false,
              datetime_pattern_value: false,
              datetime_value: false,
              integer_value: true,
              large_analog_value: true,
              octet_string_value: false,
              positive_integer_value: false,
              time_pattern_value: false,
              time_value: false,
              notification_forwarder: false,
              alert_enrollment: false,
              channel: false,
              lighting_output: false,
              binary_lighting_output: false,
              network_port: true,
              elevator_group: false,
              escalator: false,
              lift: true
            }} =
             ObjectTypesSupported.parse(
               bitstring:
                 {true, true, true, true, true, true, true, true, true, true, true, true, true,
                  true, true, true, true, true, true, true, true, false, false, true, true, true,
                  false, true, false, true, false, false, false, false, false, false, false,
                  false, false, true, false, false, false, false, false, true, true, false, false,
                  false, false, false, false, false, false, false, true, false, false, true}
             )
  end

  test "decode ObjectTypesSupported with less provided defaults to false" do
    assert {:ok,
            %ObjectTypesSupported{
              analog_input: true,
              analog_output: true,
              analog_value: true,
              binary_input: false,
              binary_output: true,
              binary_value: false,
              calendar: false,
              command: false,
              device: false,
              event_enrollment: false,
              file: false,
              group: false,
              loop: false,
              multi_state_input: false,
              multi_state_output: false,
              notification_class: false,
              program: false,
              schedule: false,
              averaging: false,
              multi_state_value: false,
              trend_log: false,
              life_safety_point: false,
              life_safety_zone: false,
              accumulator: false,
              pulse_converter: false,
              event_log: false,
              global_group: false,
              trend_log_multiple: false,
              load_control: false,
              structured_view: false,
              access_door: false,
              timer: false,
              access_credential: false,
              access_point: false,
              access_rights: false,
              access_user: false,
              access_zone: false,
              credential_data_input: false,
              network_security: false,
              bitstring_value: false,
              character_string_value: false,
              date_pattern_value: false,
              date_value: false,
              datetime_pattern_value: false,
              datetime_value: false,
              integer_value: false,
              large_analog_value: false,
              octet_string_value: false,
              positive_integer_value: false,
              time_pattern_value: false,
              time_value: false,
              notification_forwarder: false,
              alert_enrollment: false,
              channel: false,
              lighting_output: false,
              binary_lighting_output: false,
              network_port: false,
              elevator_group: false,
              escalator: false,
              lift: false
            }} = ObjectTypesSupported.parse(bitstring: {true, true, true, false, true})
  end

  test "decode ObjectTypesSupported with ApplicationTags.Encoding and less provided defaults to false" do
    assert {:ok,
            %ObjectTypesSupported{
              analog_input: true,
              analog_output: true,
              analog_value: true,
              binary_input: false,
              binary_output: true,
              binary_value: false,
              calendar: false,
              command: false,
              device: false,
              event_enrollment: false,
              file: false,
              group: false,
              loop: false,
              multi_state_input: false,
              multi_state_output: false,
              notification_class: false,
              program: false,
              schedule: false,
              averaging: false,
              multi_state_value: false,
              trend_log: false,
              life_safety_point: false,
              life_safety_zone: false,
              accumulator: false,
              pulse_converter: false,
              event_log: false,
              global_group: false,
              trend_log_multiple: false,
              load_control: false,
              structured_view: false,
              access_door: false,
              timer: false,
              access_credential: false,
              access_point: false,
              access_rights: false,
              access_user: false,
              access_zone: false,
              credential_data_input: false,
              network_security: false,
              bitstring_value: false,
              character_string_value: false,
              date_pattern_value: false,
              date_value: false,
              datetime_pattern_value: false,
              datetime_value: false,
              integer_value: false,
              large_analog_value: false,
              octet_string_value: false,
              positive_integer_value: false,
              time_pattern_value: false,
              time_value: false,
              notification_forwarder: false,
              alert_enrollment: false,
              channel: false,
              lighting_output: false,
              binary_lighting_output: false,
              network_port: false,
              elevator_group: false,
              escalator: false,
              lift: false
            }} =
             ObjectTypesSupported.parse(
               Encoding.create!({:bitstring, {true, true, true, false, true}})
             )
  end

  test "decode ObjectTypesSupported invalid tags" do
    assert {:error, :invalid_tags} = ObjectTypesSupported.parse([])
    assert {:error, :invalid_tags} = ObjectTypesSupported.parse(real: 0.0)
  end

  test "encode ObjectTypesSupported" do
    assert {:ok,
            [
              bitstring:
                {true, true, true, true, true, true, true, true, true, true, true, true, true,
                 true, true, true, true, true, true, true, true, false, false, true, true, true,
                 false, true, false, true, false, false, false, false, false, false, false, false,
                 false, true, false, false, false, false, false, true, true, false, false, false,
                 false, false, false, false, false, false, true, false, false, false}
            ]} =
             ObjectTypesSupported.encode(%ObjectTypesSupported{
               analog_input: true,
               analog_output: true,
               analog_value: true,
               binary_input: true,
               binary_output: true,
               binary_value: true,
               calendar: true,
               command: true,
               device: true,
               event_enrollment: true,
               file: true,
               group: true,
               loop: true,
               multi_state_input: true,
               multi_state_output: true,
               notification_class: true,
               program: true,
               schedule: true,
               averaging: true,
               multi_state_value: true,
               trend_log: true,
               life_safety_point: false,
               life_safety_zone: false,
               accumulator: true,
               pulse_converter: true,
               event_log: true,
               global_group: false,
               trend_log_multiple: true,
               load_control: false,
               structured_view: true,
               access_door: false,
               timer: false,
               access_credential: false,
               access_point: false,
               access_rights: false,
               access_user: false,
               access_zone: false,
               credential_data_input: false,
               network_security: false,
               bitstring_value: true,
               character_string_value: false,
               date_pattern_value: false,
               date_value: false,
               datetime_pattern_value: false,
               datetime_value: false,
               integer_value: true,
               large_analog_value: true,
               octet_string_value: false,
               positive_integer_value: false,
               time_pattern_value: false,
               time_value: false,
               notification_forwarder: false,
               alert_enrollment: false,
               channel: false,
               lighting_output: false,
               binary_lighting_output: false,
               network_port: true,
               elevator_group: false,
               escalator: false,
               lift: false
             })
  end

  test "encode ObjectTypesSupported 2" do
    assert {:ok,
            [
              bitstring:
                {true, true, true, true, true, true, true, true, true, true, true, true, true,
                 true, true, true, true, true, true, true, true, false, false, true, true, true,
                 false, true, false, true, false, false, false, false, false, false, false, false,
                 false, true, false, false, false, false, false, true, true, false, false, false,
                 false, false, false, false, false, false, true, false, false, true}
            ]} =
             ObjectTypesSupported.encode(%ObjectTypesSupported{
               analog_input: true,
               analog_output: true,
               analog_value: true,
               binary_input: true,
               binary_output: true,
               binary_value: true,
               calendar: true,
               command: true,
               device: true,
               event_enrollment: true,
               file: true,
               group: true,
               loop: true,
               multi_state_input: true,
               multi_state_output: true,
               notification_class: true,
               program: true,
               schedule: true,
               averaging: true,
               multi_state_value: true,
               trend_log: true,
               life_safety_point: false,
               life_safety_zone: false,
               accumulator: true,
               pulse_converter: true,
               event_log: true,
               global_group: false,
               trend_log_multiple: true,
               load_control: false,
               structured_view: true,
               access_door: false,
               timer: false,
               access_credential: false,
               access_point: false,
               access_rights: false,
               access_user: false,
               access_zone: false,
               credential_data_input: false,
               network_security: false,
               bitstring_value: true,
               character_string_value: false,
               date_pattern_value: false,
               date_value: false,
               datetime_pattern_value: false,
               datetime_value: false,
               integer_value: true,
               large_analog_value: true,
               octet_string_value: false,
               positive_integer_value: false,
               time_pattern_value: false,
               time_value: false,
               notification_forwarder: false,
               alert_enrollment: false,
               channel: false,
               lighting_output: false,
               binary_lighting_output: false,
               network_port: true,
               elevator_group: false,
               escalator: false,
               lift: true
             })
  end

  test "new ObjectTypesSupported with local supported object types" do
    assert %ObjectTypesSupported{
             analog_input: true,
             analog_output: true,
             analog_value: true,
             binary_input: true,
             binary_output: true,
             binary_value: true,
             calendar: true,
             command: true,
             device: true,
             event_enrollment: true,
             file: true,
             group: true,
             loop: true,
             multi_state_input: true,
             multi_state_output: true,
             notification_class: true,
             program: true,
             schedule: true,
             averaging: true,
             multi_state_value: true,
             trend_log: true,
             life_safety_point: false,
             life_safety_zone: false,
             accumulator: true,
             pulse_converter: true,
             event_log: true,
             global_group: false,
             trend_log_multiple: true,
             load_control: false,
             structured_view: true,
             access_door: false,
             timer: false,
             access_credential: false,
             access_point: false,
             access_rights: false,
             access_user: false,
             access_zone: false,
             credential_data_input: false,
             network_security: false,
             bitstring_value: true,
             character_string_value: true,
             date_pattern_value: true,
             date_value: true,
             datetime_pattern_value: true,
             datetime_value: true,
             integer_value: true,
             large_analog_value: true,
             octet_string_value: true,
             positive_integer_value: true,
             time_pattern_value: true,
             time_value: true,
             notification_forwarder: false,
             alert_enrollment: false,
             channel: false,
             lighting_output: false,
             binary_lighting_output: false,
             network_port: false,
             elevator_group: false,
             escalator: false,
             lift: false
           } = ObjectTypesSupported.new()
  end
end
